const IPC_MESSAGES = {
    SHOW_PLAYER_NAME: "SHOW_PLAYER_NAME",
    SHOW_SKIN_VIEWER: "SHOW_SKIN_VIEWER",
    SHOW_SERVER_STATUS: "SHOW_SERVER_STATUS",
    USE_OFFICIAL_JRE: "USE_OFFICIAL_JRE",
    RUN_MINECRAFT_DIRECTLY: "RUN_MINECRAFT_DIRECTLY",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    RUN_MINECRAFT: "RUN_MINECRAFT"
}

module.exports = {
    IPC_MESSAGES: IPC_MESSAGES
}