const IPC_MESSAGES = {
    SHOW_WELCOME_MESSAGE: "SHOW_WELCOME_MESSAGE",
    SHOW_RUN_STATUS: "SHOW_RUN_STATUS",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    RUN_MINECRAFT: "RUN_MINECRAFT"
}

module.exports = {
    IPC_MESSAGES: IPC_MESSAGES
}